app = "sonnet18ai"
primary_region = "lhr"

[http_service]
  internal_port = 8000
  force_https = true

[checks]
  [checks.alive]
    type = "tcp"
    interval = "15s"
    timeout = "2s"
    grace_period = "5s"
